version: 2.1

jobs:
  build:
    working_directory: ~/build-image
    machine:
      image: ubuntu-2004:2022.04.2
    #environment:
    #  COMMIT_HASH: $(echo $CIRCLE_SHA1 | cut -c -7)  
    steps:
      - checkout
      #- run: sudo apt-get install docker -y
      - run: echo $CIRCLE_SHA1
      - run:
          name: Build docker image
          command: |
            docker build -t saiakhil46/circleci-build:$(echo $CIRCLE_SHA1 | cut -c -7) .
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin    
            docker push saiakhil46/circleci-build:$(echo $CIRCLE_SHA1 | cut -c -7)
      - run:
          name: Update image in helm chart
          command: |
            SHORT_HASH=$(echo $CIRCLE_SHA1 | cut -c -7)
            echo $SHORT_HASH
            git clone https://github.com/saiakhil46/argocd-deploy.git -b master
            cd argocd-deploy
            current_version=$(cat helm-chart/circleci-build/values.yaml | grep repository: | awk '{print $2}')
            sed -i "s|$current_version|saiakhil46/circleci-build:$SHORT_HASH|g" helm-chart/circleci-build/values.yaml
            cat helm-chart/circleci-build/values.yaml
            git config credential.helper 'cache --timeout=120'
            git config user.email "saiakhil46@gmail.com"
            git config user.name "saiakhil46"
            #git commit --allow-empty -m "Tag Updated"
            git add .
            git commit -m "Updated Tag"
            # Push quietly to prevent showing the token in log
            git push -q https://${GITHUB_TOKEN}@github.com/saiakhil46/argocd-deploy.git master

workflows:
  build_flow:
    jobs:
      - build     